services:
  - type: web
    name: sasta-coder-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python render_main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MY_USER_ID
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: MEMORY_REPO
        value: advik08k/sasta-coder
      - key: GEMINI_MODEL
        value: gemini-3.6-flash
    plan: free
    healthCheckPath: /
